import QtQuick 2.0

Item {
    property int maxItems: -1

    property variant sources: []
    property variant eTags: []
    property variant jsons: []
    property bool initialized: false


    function getETag(source) {
        init()
        var index = sources.indexOf(source)
        console.log("index of " + source + " is " + index)
        if (index >= 0) return eTags[index]
        return ''
    }

    function getJson(source) {
        init()
        var index = sources.indexOf(source)
        if (index >= 0) return jsons[index]
        return ''
    }

    function put(source, eTag, json) {
        var index = sources.indexOf(source)

        console.log("====PUT " + source + "  eTag " + eTag)
        //console.log(json)
        console.log("index of " + source + " is " + index)

        var copy // funny copying needed because variants are immutable
        if (index >= 0) {
            copy = sources
            copy[index] = source
            sources = copy
            copy = eTags
            copy[index] = eTag
            eTags = copy
            copy = jsons
            copy[index] = json
            jsons = copy
        } else {
            copy = sources
            copy.push(source)
            sources = copy
            copy = eTags
            copy.push(eTag)
            eTags = copy
            copy = jsons
            copy.push(json)
            jsons = copy
        }
        console.log("sources.length" + sources.length)
        //console.log(sources)

        var length = sources.length
        if (maxItems > -1 && maxItems > length) {
            log.console("Should trim cache if needed")
            sources = sources.slice(length - maxLength)
            eTags = eTags.slice(length - maxLength)
            jsons = jsons.slice(length - maxLength)
        }
    }

    function init() {
        if (initialized) return
        initialized = true
        if (maxItems == -1) {
            put("http://cfp.devoxx.be/api/conferences/DV15/schedules",
                "941982863",
                "{
\"links\":
[
{
\"href\": \"http://cfp.devoxx.be/api/conferences/DV15/schedules/monday/\",
\"rel\": \"http://cfp.devoxx.be/api/profile/schedule\",
\"title\": \"Monday, 9th November 2015\"
},
{

\"href\": \"http://cfp.devoxx.be/api/conferences/DV15/schedules/tuesday/\",
\"rel\": \"http://cfp.devoxx.be/api/profile/schedule\",
\"title\": \"Tuesday, 10th November 2015\"
},
{
\"href\": \"http://cfp.devoxx.be/api/conferences/DV15/schedules/wednesday/\",
\"rel\": \"http://cfp.devoxx.be/api/profile/schedule\",
\"title\": \"Wednesday, 11th November 2015\"
},
{
\"href\": \"http://cfp.devoxx.be/api/conferences/DV15/schedules/thursday/\",
\"rel\": \"http://cfp.devoxx.be/api/profile/schedule\",
\"title\": \"Thursday, 12th November 2015\"
},
{
\"href\": \"http://cfp.devoxx.be/api/conferences/DV15/schedules/friday/\",
\"rel\": \"http://cfp.devoxx.be/api/profile/schedule\",
\"title\": \"Friday, 13th November 2015\"
}
]
}")
            put("http://cfp.devoxx.be/api/conferences",
                "",
                "{
\"content\": \"All conferences\",
\"links\":
[
{
\"href\": \"http://cfp.devoxx.be/api/conferences/DV15\",
\"rel\": \"http://cfp.devoxx.be/api/profile/conference\",
\"title\": \"See more details about Devoxx Belgium 2015\"
}
]
}")
            put("http://cfp.devoxx.be/api/conferences/DV15/schedules/monday/",
                "testing",
                "{\"slots\":[
{\"roomId\":\"a_hall\",\"notAllocated\":false,\"fromTimeMillis\":1447052400000,\"break\":{\"id\":\"reg\",\"nameEN\":\"Registration, Welcome and Breakfast\",\"nameFR\":\"Accueil\",\"room\":{\"id\":\"a_hall\",\"name\":\"Exhibition floor\",\"capacity\":1500,\"setup\":\"special\"}},\"roomSetup\":\"special\",\"talk\":null,\"fromTime\":\"08:00\",\"toTimeMillis\":1447057800000,\"toTime\":\"09:30\",\"roomCapacity\":1500,\"roomName\":\"Exhibition floor\",\"slotId\":\"reg_monday_9_8h0_8h30\",\"day\":\"monday\"},
{\"roomId\":\"room4\",\"notAllocated\":false,\"fromTimeMillis\":1447057800000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"mobile\",\"talkType\":\"University\",\"track\":\"Mobile\",\"summaryAsHtml\":\"<p>We will show you the same application, developed for the three most renowned smartwatch platforms, namely the Pebble, Android Wear and Apple Watch. We will show you the tools, languages, APIs and capabilities of each platform so that you can get a feel for the kind of opportunities offered by this new usage paradigm and the investment required to leverage those opportunities. Be advised there will be some C, Java and Swift in this presentation.</p>\\n\",\"id\":\"WJD-3996\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/2cccded8e04230f783be71cfc810ac894ad172eb\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Sebastien Arbogast\"},\"name\":\"Sebastien Arbogast\"},{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/35074b2d9c53c2d2ccf8ffaf446f64f7f47a111d\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Said Eloudrhiri\"},\"name\":\"Said Eloudrhiri\"}],\"title\":\"Apps On Your Wrist\",\"lang\":\"en\",\"summary\":\"We will show you the same application, developed for the three most renowned smartwatch platforms, namely the Pebble, Android Wear and Apple Watch. We will show you the tools, languages, APIs and capabilities of each platform so that you can get a feel for the kind of opportunities offered by this new usage paradigm and the investment required to leverage those opportunities. Be advised there will be some C, Java and Swift in this presentation.\"},\"fromTime\":\"09:30\",\"toTimeMillis\":1447068600000,\"toTime\":\"12:30\",\"roomCapacity\":347,\"roomName\":\"Room 4\",\"slotId\":\"uni_room4_monday_9_9h30_12h30\",\"day\":\"monday\"},
{\"roomId\":\"room5\",\"notAllocated\":false,\"fromTimeMillis\":1447057800000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"java\",\"talkType\":\"University\",\"track\":\"Java SE\",\"summaryAsHtml\":\"<p>The introduction of functional interfaces in Java 8 allows to easily use the concepts of functional programming in Java. But Java is still an OOP language, and i think it&#x27;s interesting to take a look at a little farther and anwser to the question how FP and OOP can be mixed together in Java 8.\\nThis talk will use the design patterns of the GoF as a common story, and show a lot of codes explaining how most of the behavioral and creational patterns can be re-written using a mix between FP and OOP in Java.</p>\\n\",\"id\":\"KSD-8798\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/9b5d822a739e3992281eb3f6e2524595d6b1ab6a\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Remi Forax\"},\"name\":\"Remi Forax\"}],\"title\":\"Design Pattern Reloaded\",\"lang\":\"en\",\"summary\":\"The introduction of functional interfaces in Java 8 allows to easily use the concepts of functional programming in Java. But Java is still an OOP language, and i think its interesting to take a look at a little farther and anwser to the question how FP and OOP can be mixed together in Java 8.\\r\\nThis talk will use the design patterns of the GoF as a common story, and show a lot of codes explaining how most of the behavioral and creational patterns can be re-written using a mix between FP and OOP in Java.\"},\"fromTime\":\"09:30\",\"toTimeMillis\":1447068600000,\"toTime\":\"12:30\",\"roomCapacity\":641,\"roomName\":\"Room 5\",\"slotId\":\"uni_room5_monday_9_9h30_12h30\",\"day\":\"monday\"},
{\"roomId\":\"room8\",\"notAllocated\":false,\"fromTimeMillis\":1447057800000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"methodevops\",\"talkType\":\"University\",\"track\":\"Methodology & DevOps\",\"summaryAsHtml\":\"<p>Containers are enabling developers to package their applications in new ways that are portable and work consistently everywhere. Docker has become the de facto standard for those portable containers in the cloud. Kubernetes provides an open source orchestration of Docker containers. This tutorial will provide an introduction to Docker and Kubernetes. The talk will explain several recipes on how to create and publish Docker images that package Java EE applications. Design patterns and anti-patterns that show how to create cluster of such applications will be shown. Replicating your environments using Docker images will be shown. Attendees will learn how Kubernetes’s self-healing mechanism can be used to create cluster of these containers.</p>\\n\",\"id\":\"ECW-1790\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/69e5596a50112585d5acdb93e0a4da47a10a6a8d\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Arun Gupta\"},\"name\":\"Arun Gupta\"}],\"title\":\"Docker and Kubernetes Recipes for Java Developers\",\"lang\":\"en\",\"summary\":\"Containers are enabling developers to package their applications in new ways that are portable and work consistently everywhere. Docker has become the de facto standard for those portable containers in the cloud. Kubernetes provides an open source orchestration of Docker containers. This tutorial will provide an introduction to Docker and Kubernetes. The talk will explain several recipes on how to create and publish Docker images that package Java EE applications. Design patterns and anti-patterns that show how to create cluster of such applications will be shown. Replicating your environments using Docker images will be shown. Attendees will learn how Kubernetes’s self-healing mechanism can be used to create cluster of these containers.\"},\"fromTime\":\"09:30\",\"toTimeMillis\":1447068600000,\"toTime\":\"12:30\",\"roomCapacity\":696,\"roomName\":\"Room 8\",\"slotId\":\"uni_room8_monday_9_9h30_12h30\",\"day\":\"monday\"},
{\"roomId\":\"room9\",\"notAllocated\":false,\"fromTimeMillis\":1447057800000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"cloud\",\"talkType\":\"University\",\"track\":\"Cloud & BigData\",\"summaryAsHtml\":\"<p>While machine learning has been used for decades, accessibility to these methods is undergoing a radical shift, with the rise of simple interfaces and implementations on distributed systems.\\nIn practice it means that more players can afford to take advantage of Machine Learning and at larger scales.</p>\\n<p>In this talk we&#x27;re going to review some introductory Machine Learning concepts, principles and illustrate them with use cases that could scale to large amount of data using Apache Spark as the processing engine.</p>\\n<p>The illustrative examples will be run directly from notebooks to provide a real life experience, from simple analysis towards how advanced machine learning can be simply applied at very large scale.</p>\\n\",\"id\":\"IAA-3193\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/64e199c5405b6e6ec6ef6629f5eb12fa622c0740\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Xavier Tordoir\"},\"name\":\"Xavier Tordoir\"},{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/106b29bd392f4d61c050c22978757d1815e1a26a\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Andy Petrella\"},\"name\":\"Andy Petrella\"}],\"title\":\"Distributed Machine Learning 101 using Apache Spark from a Browser\",\"lang\":\"en\",\"summary\":\"While machine learning has been used for decades, accessibility to these methods is undergoing a radical shift, with the rise of simple interfaces and implementations on distributed systems. \\r\\nIn practice it means that more players can afford to take advantage of Machine Learning and at larger scales.\\r\\n\\r\\nIn this talk we're going to review some introductory Machine Learning concepts, principles and illustrate them with use cases that could scale to large amount of data using Apache Spark as the processing engine.\\r\\n\\r\\nThe illustrative examples will be run directly from notebooks to provide a real life experience, from simple analysis towards how advanced machine learning can be simply applied at very large scale.\"},\"fromTime\":\"09:30\",\"toTimeMillis\":1447068600000,\"toTime\":\"12:30\",\"roomCapacity\":393,\"roomName\":\"Room 9\",\"slotId\":\"uni_room9_monday_9_9h30_12h30\",\"day\":\"monday\"},
{\"roomId\":\"room10\",\"notAllocated\":false,\"fromTimeMillis\":1447057800000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"lang\",\"talkType\":\"University\",\"track\":\"JVM Languages\",\"summaryAsHtml\":\"<p>In this talk we&#x27;ll explore some techniques you can use when implementing a DDD/CQRS application using Akka and Scala.</p>\\n<p>First we&#x27;ll show how we can use the Scala Type System to build a domain model based on case classes and functional paradigms. Contrary to what the common sense dictates, we&#x27;ll demonstrate that functional programming is a very good fit for domain modeling.</p>\\n<p>Secondly we&#x27;ll explore the available options when integrating it with Akka and Akka Persistence.</p>\\n<p>We&#x27;ll cover the following points:</p>\\n<ul>\\n<li>The advantages and pitfalls of using Akka as a messaging subsystem</li>\\n<li>How to reliably propagate events from the command side to the query side of your CQRS application</li>\\n<li>How to recover from failure</li>\\n<li>How to fit it in an asynchronous programming model</li>\\n</ul>\\n<p>We&#x27;ll wrap-up the talk with a short demo application built on Play and Akka.</p>\\n\",\"id\":\"KRN-1686\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/20cd4bbd2a4f2f3bbec8e450b2c978e0551f594e\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Renato Cavalcanti\"},\"name\":\"Renato Cavalcanti\"}],\"title\":\"Field guide to DDD/CQRS using the Scala Type System and Akka\",\"lang\":\"en\",\"summary\":\"In this talk we'll explore some techniques you can use when implementing a DDD/CQRS application using Akka and Scala. \\r\\n\\r\\nFirst we'll show how we can use the Scala Type System to build a domain model based on case classes and functional paradigms. Contrary to what the common sense dictates, we'll demonstrate that functional programming is a very good fit for domain modeling.\\r\\n\\r\\nSecondly we'll explore the available options when integrating it with Akka and Akka Persistence. \\r\\n\\r\\nWe'll cover the following points:\\r\\n\\r\\n- The advantages and pitfalls of using Akka as a messaging subsystem \\r\\n- How to reliably propagate events from the command side to the query side of your CQRS application\\r\\n- How to recover from failure\\r\\n- How to fit it in an asynchronous programming model\\r\\n\\r\\nWe'll wrap-up the talk with a short demo application built on Play and Akka.\"},\"fromTime\":\"09:30\",\"toTimeMillis\":1447068600000,\"toTime\":\"12:30\",\"roomCapacity\":286,\"roomName\":\"Room 10\",\"slotId\":\"uni_room10_monday_9_9h30_12h30\",\"day\":\"monday\"},
{\"roomId\":\"a_hall\",\"notAllocated\":false,\"fromTimeMillis\":1447068600000,\"break\":{\"id\":\"lunch\",\"nameEN\":\"Lunch\",\"nameFR\":\"Pause déjeuner\",\"room\":{\"id\":\"a_hall\",\"name\":\"Exhibition floor\",\"capacity\":1500,\"setup\":\"special\"}},\"roomSetup\":\"special\",\"talk\":null,\"fromTime\":\"12:30\",\"toTimeMillis\":1447072200000,\"toTime\":\"13:30\",\"roomCapacity\":1500,\"roomName\":\"Exhibition floor\",\"slotId\":\"lunch_monday_9_12h30_12h30\",\"day\":\"monday\"},
{\"roomId\":\"room4\",\"notAllocated\":false,\"fromTimeMillis\":1447072200000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"archisec\",\"talkType\":\"University\",\"track\":\"Architecture & Security\",\"summaryAsHtml\":\"<p>After numerous presentation on the JSR107, this in-depth 3 hour university session will twist the problem upside down. Instead of leading you through every aspect of the new Caching API for Java, we&#x27;ll start from a real Java application, looking at its architecture, measure contention points and slowly start adding different caching patterns to it.\\nWe&#x27;ll look beyond the specification as well, not in terms of proprietary APIs, but in terms of different cache topologies (onheap, offheap, distributed, ...) and considerations around them when introducing caching to both an existing or architecting a new one.\\nFinally, we shall look at how different application containers and framework may affect decisions we&#x27;ve made during the session.</p>\\n\",\"id\":\"KVW-1306\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/d7171cf35b79b53b2a4bb43e9bf32542f75ba5c2\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Alex Snaps\"},\"name\":\"Alex Snaps\"},{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/13df3212eb1d6abc512ca9e87383a24c18be91b4\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Louis Jacomet\"},\"name\":\"Louis Jacomet\"}],\"title\":\"Caching 101: Caching on the JVM (and beyond)\",\"lang\":\"en\",\"summary\":\"After numerous presentation on the JSR107, this in-depth 3 hour university session will twist the problem upside down. Instead of leading you through every aspect of the new Caching API for Java, we'll start from a real Java application, looking at its architecture, measure contention points and slowly start adding different caching patterns to it.\\r\\nWe'll look beyond the specification as well, not in terms of proprietary APIs, but in terms of different cache topologies (onheap, offheap, distributed, ...) and considerations around them when introducing caching to both an existing or architecting a new one.\\r\\nFinally, we shall look at how different application containers and framework may affect decisions we've made during the session. \"},\"fromTime\":\"13:30\",\"toTimeMillis\":1447083000000,\"toTime\":\"16:30\",\"roomCapacity\":347,\"roomName\":\"Room 4\",\"slotId\":\"uni_room4_monday_9_13h30_16h30\",\"day\":\"monday\"},
{\"roomId\":\"room5\",\"notAllocated\":false,\"fromTimeMillis\":1447072200000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"web\",\"talkType\":\"University\",\"track\":\"Web & HTML5\",\"summaryAsHtml\":\"<p>This session will give you a thorough introduction into Web Components. We start by explaining the standards that form the foundation of WebComponents: Template tag, custom elements, Shadow DOM, and HTML imports. Next we will do a live coding session showing you how you can rapidly build a web application with existing Web Components from Polymer Elements and other sources and connect the application to a server. In the last section, we are going to explain how you can build your own custom components and integrate them into your application. Also we will share our experience gained while building an application with Web Components and talk about pitfalls that should be avoided when using Web Components in a real world project.</p>\\n\",\"id\":\"OVY-1576\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/115f16d3b40e20d557718320e43ca5ff56d25d10\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Michael Heinrichs\"},\"name\":\"Michael Heinrichs\"},{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/03e373a7eb6756dafeccad225bff7576d6f2d86b\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Hendrik Ebbers\"},\"name\":\"Hendrik Ebbers\"}],\"title\":\"Building modern web UIs with Web Components\",\"lang\":\"en\",\"summary\":\"This session will give you a thorough introduction into Web Components. We start by explaining the standards that form the foundation of WebComponents: Template tag, custom elements, Shadow DOM, and HTML imports. Next we will do a live coding session showing you how you can rapidly build a web application with existing Web Components from Polymer Elements and other sources and connect the application to a server. In the last section, we are going to explain how you can build your own custom components and integrate them into your application. Also we will share our experience gained while building an application with Web Components and talk about pitfalls that should be avoided when using Web Components in a real world project.\"},\"fromTime\":\"13:30\",\"toTimeMillis\":1447083000000,\"toTime\":\"16:30\",\"roomCapacity\":641,\"roomName\":\"Room 5\",\"slotId\":\"uni_room5_monday_9_13h30_16h30\",\"day\":\"monday\"},
{\"roomId\":\"room8\",\"notAllocated\":false,\"fromTimeMillis\":1447072200000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"java\",\"talkType\":\"University\",\"track\":\"Java SE\",\"summaryAsHtml\":\"<p>The Stream API is among the most important API introduced in the JDK 8. New patterns have been introduced, enabling new ways to process data, especially in parallel. The Java 8 Stream API is not alone on this segment. We would like to present here RxJava, a popular API, brought by Netflix. The patterns offered by this API are quite different from the Stream API. This presentation compares those two APIs, from the developer point of view. What patterns are proposed on both sides, and what are the performances of those patterns. Many examples and benchmarks (using JMH) are shown. The goal is not to state which one of those APIs is the best, but merely give keys to decide which one is the best suited for my application.</p>\\n\",\"id\":\"XQF-4209\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/35a6797008ce8295fcc76c03dcf0a58a07ab3070\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"José Paumard\"},\"name\":\"José Paumard\"}],\"title\":\"Java 8 Stream and RxJava comparison: patterns and performances\",\"lang\":\"en\",\"summary\":\"The Stream API is among the most important API introduced in the JDK 8. New patterns have been introduced, enabling new ways to process data, especially in parallel. The Java 8 Stream API is not alone on this segment. We would like to present here RxJava, a popular API, brought by Netflix. The patterns offered by this API are quite different from the Stream API. This presentation compares those two APIs, from the developer point of view. What patterns are proposed on both sides, and what are the performances of those patterns. Many examples and benchmarks (using JMH) are shown. The goal is not to state which one of those APIs is the best, but merely give keys to decide which one is the best suited for my application. \\r\\n\"},\"fromTime\":\"13:30\",\"toTimeMillis\":1447083000000,\"toTime\":\"16:30\",\"roomCapacity\":696,\"roomName\":\"Room 8\",\"slotId\":\"uni_room8_monday_9_13h30_16h30\",\"day\":\"monday\"},
{\"roomId\":\"room8\",\"notAllocated\":false,\"fromTimeMillis\":1447086300000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"java\",\"talkType\":\"Tools-in-Action\",\"track\":\"Java SE\",\"summaryAsHtml\":\"<p>Automated testing is a must nowadays.</p>\\n<p>Nevertheless developers often skip writing automated UI tests because it&#x27;s tricky and boring. But now we have a simple and powerful tool that makes writing UI tests really effective.</p>\\n<p>Selenide is an open-source library for writing concise and stable UI tests in Java. With Selenide you can forget all these timing issues, ajax and browser whims. You can concentrate on business logic.</p>\\n<p>During my session I will demonstrate how you can write readable and stable tests that assure your application works after any changes and serve as an executable documentation. I will see it&#x27;s really easy.</p>\\n\",\"id\":\"QBD-3461\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/86e7ccf15b3b4c9f91af3ad24d6253e1771d9829\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Andrei Solntsev\"},\"name\":\"Andrei Solntsev\"}],\"title\":\"Selenide: concise UI Tests in Java. From developers for developers.\",\"lang\":\"en\",\"summary\":\"Automated testing is a must nowadays.\\r\\n\\r\\nNevertheless developers often skip writing automated UI tests because it's tricky and boring. But now we have a simple and powerful tool that makes writing UI tests really effective.\\r\\n\\r\\nSelenide is an open-source library for writing concise and stable UI tests in Java. With Selenide you can forget all these timing issues, ajax and browser whims. You can concentrate on business logic. \\r\\n\\r\\nDuring my session I will demonstrate how you can write readable and stable tests that assure your application works after any changes and serve as an executable documentation. I will see it's really easy.\"},\"fromTime\":\"17:25\",\"toTimeMillis\":1447088100000,\"toTime\":\"17:55\",\"roomCapacity\":696,\"roomName\":\"Room 8\",\"slotId\":\"tia_room8_monday_9_17h25_17h55\",\"day\":\"monday\"},
{\"roomId\":\"room9\",\"notAllocated\":false,\"fromTimeMillis\":1447086300000,\"break\":null,\"roomSetup\":\"theatre\",\"talk\":{\"trackId\":\"web\",\"talkType\":\"Tools-in-Action\",\"track\":\"Web & HTML5\",\"summaryAsHtml\":\"<p>So you decided to follow the fashion and just went for the XXXX Javascript Framework  for the front part of your application, or even more you made the big jump and decided to go with a full stack JavaScript application.So now, how are you going to debug this application? Do you still do this old « alert » debugging or are there some better ways to debug JavaScript ?\\nDuring this tool in action, I will show you the modern state of Javascript debugging. Do you know that you can have some logs with formatting in the browser console or that you can choose between six types of breakpoints ? Do you know how to take advantage of the dynamic aspect of JavaScript to help you to debug your application ?\\nDemonstrations will be done using Chrome dev tools, but most of the tips will be applicable with other browsers.</p>\\n\",\"id\":\"MLP-5950\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/179089d7dc63395c9079c6dfbda72bad2f21a6cc\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Christophe Jollivet\"},\"name\":\"Christophe Jollivet\"}],\"title\":\"Modern JavaScript debugging\",\"lang\":\"en\",\"summary\":\"So you decided to follow the fashion and just went for the XXXX Javascript Framework  for the front part of your application, or even more you made the big jump and decided to go with a full stack JavaScript application.So now, how are you going to debug this application? Do you still do this old « alert » debugging or are there some better ways to debug JavaScript ?\\r\\nDuring this tool in action, I will show you the modern state of Javascript debugging. Do you know that you can have some logs with formatting in the browser console or that you can choose between six types of breakpoints ? Do you know how to take advantage of the dynamic aspect of JavaScript to help you to debug your application ?\\r\\nDemonstrations will be done using Chrome dev tools, but most of the tips will be applicable with other browsers.\"},\"fromTime\":\"17:25\",\"toTimeMillis\":1447088100000,\"toTime\":\"17:55\",\"roomCapacity\":393,\"roomName\":\"Room 9\",\"slotId\":\"tia_room9_monday_9_17h25_17h55\",\"day\":\"monday\"},
{\"roomId\":\"bof2\",\"notAllocated\":false,\"fromTimeMillis\":1447099200000,\"break\":null,\"roomSetup\":\"classroom\",\"talk\":{\"trackId\":\"cloud\",\"talkType\":\"BOF (Bird of a Feather)\",\"track\":\"Cloud & BigData\",\"summaryAsHtml\":\"<p>Remember the excitement you felt when pulling a box off the shelf complete with CD and user guides? Remember your dismay when you wanted to reinstall and couldn’t find your CD? Remember software vendors sweating over the logistics of distributing physical products? Well, that’s all in the past. Today we just click a link and download software from our vendor’s cloud storage. Sounds great, but our vendor is still unhappy. He wants to know which versions were downloaded, by whom, when and from where. A smart software distribution platform that is structured for distribution, fully understanding versions and metadata, can provide you with that critical information which you can use in your sales and marketing efforts. You can have that today.</p>\\n\",\"id\":\"ZOD-7008\",\"speakers\":[{\"link\":{\"href\":\"http://cfp.devoxx.be/api/conferences/DV15/speakers/57d34c71dfb2d1c172d6da39e1ba39aa1ea7aa42\",\"rel\":\"http://cfp.devoxx.be/api/profile/speaker\",\"title\":\"Baruch Sadogursky\"},\"name\":\"Baruch Sadogursky\"}],\"title\":\"Software Distribution: Past, Present and Future\",\"lang\":\"en\",\"summary\":\"Remember the excitement you felt when pulling a box off the shelf complete with CD and user guides? Remember your dismay when you wanted to reinstall and couldn’t find your CD? Remember software vendors sweating over the logistics of distributing physical products? Well, that’s all in the past. Today we just click a link and download software from our vendor’s cloud storage. Sounds great, but our vendor is still unhappy. He wants to know which versions were downloaded, by whom, when and from where. A smart software distribution platform that is structured for distribution, fully understanding versions and metadata, can provide you with that critical information which you can use in your sales and marketing efforts. You can have that today.\"},\"fromTime\":\"21:00\",\"toTimeMillis\":1447102800000,\"toTime\":\"22:00\",\"roomCapacity\":70,\"roomName\":\"BOF 2\",\"slotId\":\"bof_bof2_monday_9_21h0_22h0\",\"day\":\"monday\"}
]}")
        }
    }
}
